### ISSUE TITLE
rpc+assets: add support for issuing an asset into an existing key_family

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#110]
Today we support the `EnableEmission` field which means we can make assets that have a specified key family. However, there's no way to then reference an existing key family during the minting operation, meaning we don't [EDIT: yet] support issuing multiple tranches of the same asset. 

A related gap is that it isn't possible to issue a set of collectibles within the same "asset group". To enable this we want to allow each request to reference some asset group ID (can be just an int), then when minting the assets, we'd use the same key family for them all.

**Comment by jharveyb** [comment]
From offline discussion:

Reissuance using an existing key family is orthogonal to issuing multiple assets into the same family at once.

Existing families can be referenced via the corresponding tweaked pubkey, which is already exposed in some RPCs but may merit a new RPC call like 'ListAssetGroups'.

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightninglabs/taro/pull/214

the second item there is being tracked in https://github.com/lightninglabs/taro/issues/233
