### ISSUE TITLE
bip-taro+proofs+commitment: account for sweep case and collectible transfer to non-interactive sends

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#121]
Historically, the name non-interactive send (using the addrs cheme) scheme was devised mainly thinking about normal asset spends. With how things are spec'd out rn, there're two major (but easily addressable gaps):
  1. You can't use the addrs to transfer collectibles 
  2. You can't completely send all of an asset using the address

Both of these are actually related. The issue that arises is that the split commitment technique lets the sender fully re-create the output of the receiver to send. This is good for the receiver as they need to know what to look for on chain. But what if the sender has no new asset to anchor the split commitment root within? 

The easiest way to address this is to allow zero value assets, but only in certain situations. These assets are essentially burnt (another way of burning assets) as they have a script key of all zeroes (can't sign w/ it) and also a zero value. The purpose of this tombstone is _only_ to anchor the split commitment so the non-interactive send case works properly. 

We also need to outline this in the BIP as well.

**Comment by dstadulis** [comment]
to note to cover: 0 values are allowed in the NUMs point
