### ISSUE TITLE
taroscript: further encapsulate the discrete send methods into a single "builder" type 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#122]
Today we have a series of utility functions that when strewn together implement the various stages of the sending logic: https://github.com/lightninglabs/taro/blob/ec89edb1212003db55b3c8625a1eb8f77d575ea8/taroscript/send.go. 

Most of the methods accept, then copy and modify the main `SendDelta` struct: https://github.com/lightninglabs/taro/blob/ec89edb1212003db55b3c8625a1eb8f77d575ea8/taroscript/send.go#L69-L92

With the current design, the caller needs to know which order to call them in, and also to make sure to pass in the same spend delta along with everything. 

IMO, we can encapsulate this state further, and just worry about the inputs the caller needs to provide, and what it wants in return:
  * Inputs:
       * Coin selection, to select the set of inputs 
       * Funded PSBT
   * Outputs:
        * PSBT skeleton for funding (can even be done in the builder type)
        * Final signed Bitcoin transaction, updated proof files, and the final send delta 

With this, the caller can provide the single input, then the builder type works internally to the point where it returns the PSBT skeleton for funding. The user then provides the funded PSBT, and the builder continues again. Finally it'll request the signed PSBT which lets it complete the process. 

In summary, we may be able to reduce things down into just a few methods/inputs:
  * `New`: passes in either the selected coins, or an interface that lets it do the coin selection. 
  * `DerivePSBT`: uses the above to create a PSBT that needs inputs for funding. 
  * `ApplyFundedPSBT`: caller takes the PSBT and does the funding, then gives it back to the builder.
  * `FinalPSBT`: caller gets the final PSBT (has the extra input added w/ all the information)
      * This could also just be a return value of the prior method 
  * `Complete`: caller gives the final PSBT and gets the final set of stuff it needs to broadcast

A good template/model here for what I have in mind is the Session/Context struct for the `musig2` package: https://pkg.go.dev/github.com/btcsuite/btcd/btcec/v2@v2.2.1/schnorr/musig2#Session

**Comment by dstadulis** [comment]
Oli is focused on this. but #75 is a prereq

**Comment by Roasbeef** [comment]
@dstadulis I think the other way around? That we want to do this before #75, since that starts to get into PSBT territory, which wants better encapsulated send flow abstractions.
