### ISSUE TITLE
bip-taro: rename key family to asset group 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#142]
Currently we use the term "asset key family" to refer to association of assets with distinct asset IDs under a single identifier. Over the past few weeks, I've been warming up more to the term "asset group" instead. IMO this is less ambiguous, in that we want to group/correlate a series of assets together. With this naming, "family key" would now be "asset group", and so on.

This is strictly a naming change, and all semantics stay the same. We likely want to package this with #41.

**Comment by dstadulis** [comment]
Ideas for alternative names:

asset collate
assetCollationID
AssetCollatorID

**Comment by dstadulis** [comment]
This issue should be P0 so the renaming gets out of the way first before we touch other Asset Group / Key Family PRs
