### ISSUE TITLE
proofs: add additional backend checks for merkle proof verification 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#143]
Today when we verify merkle proofs for the inclusion proof of an asset's existence, we properly verify that the root hash we derive matches the block hash. However, a number of other important checks such as bits/pow/mainchain are missing. We should add these additional checks as well, re-using much of the logic that already lives in the `neutrino` package. 

This issue tracks the following TOOD originally left in the code: https://github.com/lightninglabs/taro/blob/main/proof/verifier.go#L256-L259

**Comment by Roasbeef** [comment]
Possible work around:
  * Take the txid of the anchor tx
  * Fetch conf ntnf, w/ block 
  * If that is returned, it's ok
  * Can also use neutrino libs to do pow verification, etc

**Comment by dstadulis** [comment]
>root hash we derive matches the block hash
matches or corresponds to the associated block hash

Point to consider:
consider implication of pool batch inclusion verification

**Comment by ffranr** [comment]
@Roasbeef what do you mean by ["Fetch conf ntnf, w/ block"](https://github.com/lightninglabs/taro/issues/143#issuecomment-1291003410) please?

**Comment by Roasbeef** [comment]
So the `RegisterTxConf` RPC call now has an optional flag that lets you fetch a block. We use this to be able to fetch the block header to create a merkle proof against when minting or doing transactions. 

We can assume that if the backend has that block, then it's actually in the main chain. So the idea here is to request a confirmation notification for the _transaction_ that anchors each proof. There's also a slimmer mode of validation, where one would just fetch enoguh/some of them. 

In terms of other extra checks, we can assume that the backend performed those checks in the first place to be able to store/fetch the blocks. However, we can also apply some _safe_ checks such as PoW, prior header connectedness, etc.

**Comment by ffranr** [comment]
Adding lnd RPC calls to facilitate block header verification: https://github.com/lightningnetwork/lnd/pull/7197



Associated draft PR: https://github.com/lightninglabs/taro/pull/199

**Comment by Roasbeef** [comment]
> Adding lnd RPC calls to facilitate block header verification

Did you run into a scenario where just using the existing registration call didn't work?

**Comment by ffranr** [comment]
Oli and Jordi recommended that this might be a good opportunity to add LND RPC calls which expose existing chain functions. They suggested that the `RegisterConfirmationsNtfn` RPC call might be a comparatively slower and more round about way of retrieving blocks.

**Comment by ffranr** [comment]
FYI This is where neutrino checks for PoW and prior header connectedness: 
https://github.com/ffranr/neutrino/blob/88d8515ef499771f13f37fc94c7f438d7bce3758/blockmanager.go#L2406-L2409

**Comment by ffranr** [comment]
Associated merged PR: https://github.com/lightninglabs/taro/pull/199
