### ISSUE TITLE
tarod: add explicit chain fee tracking for all relevant operations

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#144]
Today we have the [`chain_txns` table](https://github.com/lightninglabs/taro/blob/3ec2b8253bf1fafc9b3659d9fe6a3396bb17fd5c/tarodb/sqlite/migrations/000002_assets.up.sql#L1-L17) that tracks all on chain transactions we do via the main transaction publication interface. In order to later allow air tight accounting of all the minting/transfer costs, we should start to _explicitly_ track the chain fee along side all transactions. Doing it here means we can always do joins to find things like relative transaction costs, amortization savings, etc. Doing it now means we don't need to go back later and either scan the chain or attempt to back populate information to fill accounting gaps later.

**Comment by dstadulis** [comment]
Doesn't need a chain backend
