### ISSUE TITLE
proof: improve robustness of hashmail proof distribution for async send flow 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#164]
Today as an interim solution, we use some of the LNC infra to help transmit the final proofs/receipts for the async send flow. 

The happy path works pretty well, however some restart cases aren't properly addressed. 

One example is in the freighter: https://github.com/lightninglabs/taro/blob/c8c24c57a844d1bd78c07fcbf44e5940bd319bcc/tarofreighter/chain_porter.go#L411-L436

This should be moved into the state machine, so we'll run this step again if re-start before things are complete. We can then track within the transfer table on disk, if we've finished proof distribution or not (the very last step). Along the way we'll need to do something similar on the receive side. The final consideration here is that the state machine needs some reliable-enough signal that it can stop trying to deliver the proof.

**Comment by dstadulis** [comment]
Let's move this to `v0.1.2`

**Comment by dstadulis** [comment]
Possibly Robyn to pick up

**Comment by ffranr** [comment]
FYI (@dstadulis), this PR will allow us to include aperture in taro: https://github.com/lightninglabs/aperture/pull/84

Which will hopefully lead to hashmail working locally for itests.
