### ISSUE TITLE
tarodb: refactor + generalize sql storage engine to support sqlite+postgres

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#174]
Today we use `sqlc` wit the _postgres_ code generation and parsing engine to support `sqlite`. Ideally we can leverage nearly the exact same pipeline to support postgres natively as well. 

Given we use the postgres codegen+parsing engine, we can be farily confident that we're writing things in simple enough SQL to have the _qeries_ be exectued by both DB endges. At a glance, the main difference between postgre+sqlite is certain datatype at the schema level. As an example, postgres has `BYTEA`, while sqlite uses `BLOB` 

Assuming the above is true, then I think we can get away with something like:
  * Use Go templating within the migration/schema files to abstract away which concrete data type we'll bind to at runtime. 
  * Abstract away the [DSN generation and config parsing](https://github.com/lightninglabs/taro/blob/main/tarodb/sqlite.go#L54-L92)
  * Render the template conditional on the DB type right before [we pass things into the file virtual file server](https://github.com/lightninglabs/taro/blob/main/tarodb/sqlite.go#L108-L117)
  * Abstract away the current `SqliteStore` into `SqlDatabase[db DbDriver]` (or something like that):
     * The DbDriver interface can expose things like parsing the config, opening the actual DB, etc, etc. 
     * We may also want to also have the config be a type param as well 
     * We could also thread through the actual binding of the template types at this layer as well 
  * Rename the current internal `sqlite` package to something like `queries` 
  * Then add implementations for sqlite+postgres for the above hypothetical struct/interface/wrapper

**Comment by dstadulis** [comment]
TODO: check if uint in postgres requires an extension
