### ISSUE TITLE
Unable to list assets: rpc error: code = Unknown desc = cannot retrieve macaroon.

### ISSUE THREAD

**Issue by lenhatquang97** [lightninglabs/taro#202]
When I run terminal with command "tarocli assets list", it says no rows in result set. How can I solve this problem?
```
[tarocli] unable to list assets: rpc error: code = Unknown desc = cannot retrieve macaroon: cannot get macaroon: sql: no rows in result set
```

My version:
Lncli version 0.15.99-beta commit=cert/v1.2.0-6-g22fec7633
Btcd version 0.23.3-beta
Tarod version 0.1.0-alpha commit=v0.1.0-alpha-33-gf91d236

**Comment by guggero** [comment]
Please try removing all old data in `~/.taro` and then try with the latest version (`v0.1.1-alpha`) of `tarod`.

**Comment by lenhatquang97** [comment]
Yeah, it works very well. Thanks!!
