### ISSUE TITLE
Bitcoind Regtest LND 0.15.99-beta commit=cert/v1.2.0-129-geca82d986 Taro Minting Error

### ISSUE THREAD

**Issue by D33r-Gee** [lightninglabs/taro#226]
While attempting to test tarod on regtest I get the following error after minting an asset:

`[ERR] GRDN: unable to advance state machine: unable to add exclusion proofs: cannot add exclusion proof, output 1 is a P2TR output but is missing the internal key in the PSBT`

I expected the taro asset to be minted and available to test with another tarod instance on regtest

**To reproduce**

I have ran the master lnd "version": "0.15.99-beta commit=cert/v1.2.0-129-geca82d986" make && make install tags=”signrpc walletrpc chainrpc routerrpc invoicesrpc chainkit”

The lnd and lncli do compile then running lnd on regtest, getinfo returns:

"version": "0.15.99-beta commit=cert/v1.2.0-129-geca82d986"
"chains": [
        {
            "chain": "bitcoin",
            "network": "regtest"
        }
    ],

Created a new p2tr address and sent funds to it from Bitcoind regtest node.

**System information**

Using Bitcoin Core Version: 249900

<!-- What type of machine are you observing the error on (OS/CPU and disk type)? →
Ubuntu 20.04 

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
Model name:                      Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

Disk type: sda

**Comment by Roasbeef** [comment]
So you'll need the latest version of lnd that starts to populate the P2TR change addr info (master for now).
