### ISSUE TITLE
input commitment does not contain asset_id=xxx: send: Input does not contain requested asset

### ISSUE THREAD

**Issue by snow884** [lightninglabs/taro#228]
I keep getting this error when sending assets:
```
[tarocli] unable to send assets: rpc error: code = Unknown desc = input commitment does not contain asset_id=2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b: send: Input does not contain requested asset
```

My setup:

My LND commit hash is: c03de26dc
My Taro commit hash is: ddb0e0d

I have built LND using the command:
```
git checkout master && make && make install tags="autopilotrpc chainkit chainrpc invoicesrpc peersrpc routerrpc signrpc walletrpc watchtowerrpc wtclientrpc"
```

How to reproduce:

Mint new currency:
```
tarocli assets mint --type normal --name "x" --supply 880 --enable_emission false --meta "x currenccy" --skip_batch
```

This always gets stuck - I have to restart tarod....

Get new address:
```
tarocli addrs new --genesis_bootstrap_info 8508d19010b7b622da41cba39da82a4d4313654bf9996470bc681d2559d870890000000103227822000000000000 --amt 4
```

Send funds to address:
```
tarocli assets send --addr tarotb1qqqsqq3ws5ydryqsk7mz9kjpew3em2p2f4p3xe2tlxvkgu9udqwj2kwcwzysqqqqqypjy7pzqqqqqqqqqqzzzq4gxa53su0rk2e9y7vv5c72s3yam4qx83zam0zuyh9ucyl32645kvrzzq5n0exqf4f4wm6au9kyhrwddcdkpr98g0anu4xyflq2tlmmenvqduyqzpqkhr8jv
```

I get the error:
```
input commitment does not contain asset_id=2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b: send: Input does not contain requested asset
```

Log from tarod:
```
2023-01-04 11:38:20.514 [INF] FRTR: Received to send request to: 2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b:02a837691871e3b2b252798ca63ca8449ddd4063c45ddbc5c25cbcc13f156ab4b3
2023-01-04 11:38:20.514 [INF] FRTR: ChainPorter advancing from state=SendStateInitializing to state=SendStateBroadcast
2023-01-04 11:38:20.518 [INF] FRTR: Selected 1 possible asset inputs for send to 02a837691871e3b2b252798ca63ca8449ddd4063c45ddbc5c25cbcc13f156ab4b3
2023-01-04 11:38:20.518 [WRN] FRTR: unable to advance state machine: input commitment does not contain asset_id=2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b: send: Input does not contain requested asset
2023-01-04 11:38:20.518 [ERR] RPCS: [/tarorpc.Taro/SendAsset]: input commitment does not contain asset_id=2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b: send: Input does not contain requested asset
2023-01-04 11:38:36.656 [INF] FRTR: New asset shipment request to addr: (*tarofreighter.AssetParcel)(0xc00038aa20)({
 Dest: (*address.Taro)(0xc0001b2c60)({
  ChainParams: (*address.ChainParams)(0xc00038a9c0)({
   Params: (*chaincfg.Params)(0x2356fa0)({
    Name: (string) (len=8) "testnet3",
    Net: (wire.BitcoinNet) TestNet3,
    DefaultPort: (string) (len=5) "18333",
    DNSSeeds: ([]chaincfg.DNSSeed) (len=4 cap=4) {
     (chaincfg.DNSSeed) testnet-seed.bitcoin.jonasschnelli.ch,
     (chaincfg.DNSSeed) testnet-seed.bitcoin.schildbach.de,
     (chaincfg.DNSSeed) seed.tbtc.petertodd.org,
     (chaincfg.DNSSeed) testnet-seed.bluematt.me
    },
    GenesisBlock: (*wire.MsgBlock)(0x2352f20)({
     Header: (wire.BlockHeader) {
      Version: (int32) 1,
      PrevBlock: (chainhash.Hash) (len=32 cap=32) 0000000000000000000000000000000000000000000000000000000000000000,
      MerkleRoot: (chainhash.Hash) (len=32 cap=32) 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b,
      Timestamp: (time.Time) 2011-02-02 23:16:42 +0000 UTC,
      Bits: (uint32) 486604799,
      Nonce: (uint32) 414098458
     },
     Transactions: ([]*wire.MsgTx) (len=1 cap=1) {
      (*wire.MsgTx)(0x2350600)({
       Version: (int32) 1,
       TxIn: ([]*wire.TxIn) (len=1 cap=1) {
        (*wire.TxIn)(0x2351dc0)({
         PreviousOutPoint: (wire.OutPoint) 0000000000000000000000000000000000000000000000000000000000000000:4294967295,
         SignatureScript: ([]uint8) (len=77 cap=77) {
          00000000  04 ff ff 00 1d 01 04 45  54 68 65 20 54 69 6d 65  |.......EThe Time|
          00000010  73 20 30 33 2f 4a 61 6e  2f 32 30 30 39 20 43 68  |s 03/Jan/2009 Ch|
          00000020  61 6e 63 65 6c 6c 6f 72  20 6f 6e 20 62 72 69 6e  |ancellor on brin|
          00000030  6b 20 6f 66 20 73 65 63  6f 6e 64 20 62 61 69 6c  |k of second bail|
          00000040  6f 75 74 20 66 6f 72 20  62 61 6e 6b 73           |out for banks|
         },
         Witness: (wire.TxWitness) <nil>,
         Sequence: (uint32) 4294967295
        })
       },
       TxOut: ([]*wire.TxOut) (len=1 cap=1) {
        (*wire.TxOut)(0x2348da0)({
         Value: (int64) 5000000000,
         PkScript: ([]uint8) (len=67 cap=67) {
          00000000  41 04 67 8a fd b0 fe 55  48 27 19 67 f1 a6 71 30  |A.g....UH'.g..q0|
          00000010  b7 10 5c d6 a8 28 e0 39  09 a6 79 62 e0 ea 1f 61  |..\..(.9..yb...a|
          00000020  de b6 49 f6 bc 3f 4c ef  38 c4 f3 55 04 e5 1e c1  |..I..?L.8..U....|
          00000030  12 de 5c 38 4d f7 ba 0b  8d 57 8a 4c 70 2b 6b f1  |..\8M....W.Lp+k.|
          00000040  1d 5f ac                                          |._.|
         }
        })
       },
       LockTime: (uint32) 0
      })
     }
    }),
    GenesisHash: (*chainhash.Hash)(0x2229440)((len=32 cap=32) 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943),
    PowLimit: (*big.Int)(0xc00007a580)(26959946667150639794667015087019630673637144422540572481103610249215),
    PowLimitBits: (uint32) 486604799,
    BIP0034Height: (int32) 21111,
    BIP0065Height: (int32) 581885,
    BIP0066Height: (int32) 330776,
    CoinbaseMaturity: (uint16) 100,
    SubsidyReductionInterval: (int32) 210000,
    TargetTimespan: (time.Duration) 336h0m0s,
    TargetTimePerBlock: (time.Duration) 10m0s,
    RetargetAdjustmentFactor: (int64) 4,
    ReduceMinDifficulty: (bool) true,
    MinDiffReductionTime: (time.Duration) 20m0s,
    GenerateSupported: (bool) false,
    Checkpoints: ([]chaincfg.Checkpoint) (len=14 cap=14) {
     (chaincfg.Checkpoint) {
      Height: (int32) 546,
      Hash: (*chainhash.Hash)(0xc00004a4c0)((len=32 cap=32) 000000002a936ca763904c3c35fce2f3556c559c0214345d31b1bcebf76acb70)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 100000,
      Hash: (*chainhash.Hash)(0xc00004a4e0)((len=32 cap=32) 00000000009e2958c15ff9290d571bf9459e93b19765c6801ddeccadbb160a1e)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 200000,
      Hash: (*chainhash.Hash)(0xc00004a500)((len=32 cap=32) 0000000000287bffd321963ef05feab753ebe274e1d78b2fd4e2bfe9ad3aa6f2)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 300001,
      Hash: (*chainhash.Hash)(0xc00004a520)((len=32 cap=32) 0000000000004829474748f3d1bc8fcf893c88be255e6d7f571c548aff57abf4)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 400002,
      Hash: (*chainhash.Hash)(0xc00004a540)((len=32 cap=32) 0000000005e2c73b8ecb82ae2dbc2e8274614ebad7172b53528aba7501f5a089)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 500011,
      Hash: (*chainhash.Hash)(0xc00004a560)((len=32 cap=32) 00000000000929f63977fbac92ff570a9bd9e7715401ee96f2848f7b07750b02)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 600002,
      Hash: (*chainhash.Hash)(0xc00004a580)((len=32 cap=32) 000000000001f471389afd6ee94dcace5ccc44adc18e8bff402443f034b07240)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 700000,
      Hash: (*chainhash.Hash)(0xc00004a5a0)((len=32 cap=32) 000000000000406178b12a4dea3b27e13b3c4fe4510994fd667d7c1e6a3f4dc1)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 800010,
      Hash: (*chainhash.Hash)(0xc00004a5c0)((len=32 cap=32) 000000000017ed35296433190b6829db01e657d80631d43f5983fa403bfdb4c1)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 900000,
      Hash: (*chainhash.Hash)(0xc00004a5e0)((len=32 cap=32) 0000000000356f8d8924556e765b7a94aaebc6b5c8685dcfa2b1ee8b41acd89b)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 1000007,
      Hash: (*chainhash.Hash)(0xc00004a600)((len=32 cap=32) 00000000001ccb893d8a1f25b70ad173ce955e5f50124261bbbc50379a612ddf)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 1100007,
      Hash: (*chainhash.Hash)(0xc00004a620)((len=32 cap=32) 00000000000abc7b2cd18768ab3dee20857326a818d1946ed6796f42d66dd1e8)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 1200007,
      Hash: (*chainhash.Hash)(0xc00004a640)((len=32 cap=32) 00000000000004f2dc41845771909db57e04191714ed8c963f7e56713a7b6cea)
     },
     (chaincfg.Checkpoint) {
      Height: (int32) 1300007,
      Hash: (*chainhash.Hash)(0xc00004a660)((len=32 cap=32) 0000000072eab69d54df75107c052b26b0395b44f77578184293bf1bb1dbd9fa)
     }
    },
    RuleChangeActivationThreshold: (uint32) 1512,
    MinerConfirmationWindow: (uint32) 2016,
    Deployments: ([5]chaincfg.ConsensusDeployment) (len=5 cap=5) {
     (chaincfg.ConsensusDeployment) {
      BitNumber: (uint8) 28,
      MinActivationHeight: (uint32) 0,
      CustomActivationThreshold: (uint32) 0,
      DeploymentStarter: (*chaincfg.MedianTimeDeploymentStarter)(0xc0000a7170)({
       blockClock: (chaincfg.BlockClock) <nil>,
       startTime: (time.Time) 2008-01-01 00:00:01 +0000 UTC
      }),
      DeploymentEnder: (*chaincfg.MedianTimeDeploymentEnder)(0xc0000a71a0)({
       blockClock: (chaincfg.BlockClock) <nil>,
       endTime: (time.Time) 2008-12-31 23:59:59 +0000 UTC
      })
     },
     (chaincfg.ConsensusDeployment) {
      BitNumber: (uint8) 22,
      MinActivationHeight: (uint32) 100000,
      CustomActivationThreshold: (uint32) 1815,
      DeploymentStarter: (*chaincfg.MedianTimeDeploymentStarter)(0xc0000a71d0)({
       blockClock: (chaincfg.BlockClock) <nil>,
       startTime: (time.Time) 0001-01-01 00:00:00 +0000 UTC
      }),
      DeploymentEnder: (*chaincfg.MedianTimeDeploymentEnder)(0xc0000a7200)({
       blockClock: (chaincfg.BlockClock) <nil>,
       endTime: (time.Time) 0001-01-01 00:00:00 +0000 UTC
      })
     },
     (chaincfg.ConsensusDeployment) {
      BitNumber: (uint8) 0,
      MinActivationHeight: (uint32) 0,
      CustomActivationThreshold: (uint32) 0,
      DeploymentStarter: (*chaincfg.MedianTimeDeploymentStarter)(0xc0000a7230)({
       blockClock: (chaincfg.BlockClock) <nil>,
       startTime: (time.Time) 2016-03-01 00:00:00 +0000 UTC
      }),
      DeploymentEnder: (*chaincfg.MedianTimeDeploymentEnder)(0xc0000a7260)({
       blockClock: (chaincfg.BlockClock) <nil>,
       endTime: (time.Time) 2017-05-01 00:00:00 +0000 UTC
      })
     },
     (chaincfg.ConsensusDeployment) {
      BitNumber: (uint8) 1,
      MinActivationHeight: (uint32) 0,
      CustomActivationThreshold: (uint32) 0,
      DeploymentStarter: (*chaincfg.MedianTimeDeploymentStarter)(0xc0000a7290)({
       blockClock: (chaincfg.BlockClock) <nil>,
       startTime: (time.Time) 2016-05-01 00:00:00 +0000 UTC
      }),
      DeploymentEnder: (*chaincfg.MedianTimeDeploymentEnder)(0xc0000a72c0)({
       blockClock: (chaincfg.BlockClock) <nil>,
       endTime: (time.Time) 2017-05-01 00:00:00 +0000 UTC
      })
     },
     (chaincfg.ConsensusDeployment) {
      BitNumber: (uint8) 2,
      MinActivationHeight: (uint32) 0,
      CustomActivationThreshold: (uint32) 1512,
      DeploymentStarter: (*chaincfg.MedianTimeDeploymentStarter)(0xc0000a72f0)({
       blockClock: (chaincfg.BlockClock) <nil>,
       startTime: (time.Time) 2021-04-24 00:00:00 +0000 UTC
      }),
      DeploymentEnder: (*chaincfg.MedianTimeDeploymentEnder)(0xc0000a7320)({
       blockClock: (chaincfg.BlockClock) <nil>,
       endTime: (time.Time) 2021-08-11 00:00:00 +0000 UTC
      })
     }
    },
    RelayNonStdTxs: (bool) true,
    Bech32HRPSegwit: (string) (len=2) "tb",
    PubKeyHashAddrID: (uint8) 111,
    ScriptHashAddrID: (uint8) 196,
    PrivateKeyID: (uint8) 239,
    WitnessPubKeyHashAddrID: (uint8) 3,
    WitnessScriptHashAddrID: (uint8) 40,
    HDPrivateKeyID: ([4]uint8) (len=4 cap=4) {
     00000000  04 35 83 94                                       |.5..|
    },
    HDPublicKeyID: ([4]uint8) (len=4 cap=4) {
     00000000  04 35 87 cf                                       |.5..|
    },
    HDCoinType: (uint32) 1
   }),
   TaroHRP: (string) (len=6) "tarotb"
  }),
  Version: (asset.Version) 0,
  Genesis: (asset.Genesis) {
   FirstPrevOut: (wire.OutPoint) 8970d859251d68bc706499f94b6513434d2aa89da3cb41da22b6b71090d10885:1,
   Tag: (string) (len=3) "\"x\"",
   Metadata: ([]uint8) {
   },
   OutputIndex: (uint32) 0,
   Type: (asset.Type) Normal
  },
  GroupKey: (*secp256k1.PublicKey)(<nil>),
  ScriptKey: (secp256k1.PublicKey) {
   x: (secp256k1.FieldVal) a837691871e3b2b252798ca63ca8449ddd4063c45ddbc5c25cbcc13f156ab4b3,
   y: (secp256k1.FieldVal) e6e149fbb6193e25a9fe3c8aafb3f42f8784950739af72f44f7c11e0aec2ef08
  },
  InternalKey: (secp256k1.PublicKey) {
   x: (secp256k1.FieldVal) 937e4c04d53576f5de16c4b8dcd6e1b608ca743fb3e54c44fc0a5ff7bccd806f,
   y: (secp256k1.FieldVal) bcbc4397a0ddab5cb2110a6fde4f724e94c6cfb5fd20621231ee3b6f2fa0bde0
  },
  Amount: (uint64) 4
 }),
 respChan: (chan *tarofreighter.PendingParcel) (cap=1) 0xc0007df4a0,
 errChan: (chan error) (cap=1) 0xc0007df440
})

2023-01-04 11:38:36.657 [INF] FRTR: Received to send request to: 2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b:02a837691871e3b2b252798ca63ca8449ddd4063c45ddbc5c25cbcc13f156ab4b3
2023-01-04 11:38:36.657 [INF] FRTR: ChainPorter advancing from state=SendStateInitializing to state=SendStateBroadcast
2023-01-04 11:38:36.661 [INF] FRTR: Selected 1 possible asset inputs for send to 02a837691871e3b2b252798ca63ca8449ddd4063c45ddbc5c25cbcc13f156ab4b3
2023-01-04 11:38:36.661 [WRN] FRTR: unable to advance state machine: input commitment does not contain asset_id=2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b: send: Input does not contain requested asset
2023-01-04 11:38:36.661 [ERR] RPCS: [/tarorpc.Taro/SendAsset]: input commitment does not contain asset_id=2955d75bc10b5ec255123414b42382f4d51b97ff22734ee7aebd255bd985f44b: send: Input does not contain requested asset
```

**Comment by Roasbeef** [comment]
Do things work if you use an `=` everywhere in the command for the CLI args vs a space (like it is rn)?

**Comment by aivansky-contractor** [comment]
@Roasbeef i will try using =

**Comment by aivansky-contractor** [comment]
@Roasbeef oddly enough I am able to generate and invoice if I supply a group key. I am not sure if that is the right way to do it though.

**Comment by jharveyb** [comment]
Also, was the mint confirmed before you tried the send? Should be some log lines about it.

**Comment by gvonbergen** [comment]
Having the same issue. 

tarod version 0.1.99-alpha commit=v0.1.1-alpha-107-ge40c078
lnd version 0.15.99-beta commit=tlv/v1.1.0-104-gef8cf73d4

**Comment by jharveyb** [comment]
I think this is an issue with CLI parsing; to enable emission, you shouldn't need `true` after `--enable-emission`. The default is no emission, and to enable you should only need to add `--enable-emission`.

@snow884 could you try the minting again with:

`tarocli assets mint --type normal --name "x" --supply 880 --enable_emission  --meta "x currenccy" --skip_batch`?

**Comment by gvonbergen** [comment]
@jharveyb I used --enable-emission true. But had to restart tarod that it worked. Without the true it worked end-to-end. But the payment error I still get. will try now to get a second instance of lnd running.

**Comment by gvonbergen** [comment]
Tried it now with two instances of lnd & tarod. Same result:

[tarocli] unable to send assets: rpc error: code = Unknown desc = input commitment does not contain asset_id=18cc53a44a8defdc22ee139fe8312a271f96202a4fd30978710bb176491e28f5: send: Input does not contain requested asset

Command is:
tarocli assets send --addr tarotb1qqqsqq3un0gcytr008ttrkzp357hxgma5pvn4mtv22r03lg6uetgccrrgnesqqqqqyzyc32cx5xhxatsv4ezqmt0dejhjgp4qqqqqqqqqsssyz3cv62gs0l2lftt8remzhklu557mq9aslrf89xdfyquas3vp6j8qcss9dq09pfqwlgcpx6u5lu6lfrahgcqdql99u7qlezxrh66hhfjmrdxpqqhjq75yfr

And the asset was confirmed on the blockchain on the the first node:
{
    "assets": [
        {
            "version": 0,
            "asset_genesis": {
                "genesis_point": "f34463608c56e61afdf886526ced3a59a07d23733d8d41d8b1d6796f2c82d19b:1",
                "name": "LEX5",
                "meta": "7375706572206d6f6e65792035",
                "asset_id": "18cc53a44a8defdc22ee139fe8312a271f96202a4fd30978710bb176491e28f5",
                "output_index": 0,
                "genesis_bootstrap_info": "9bd1822c6f79d6b1d8418d3d73237da0593aed6c5286f8fd1ae6568c606344f300000001044c4558350d7375706572206d6f6e657920350000000000",
                "version": 0
            },
            "asset_type": "NORMAL",
            "amount": "1000",
            "lock_time": 0,
            "relative_lock_time": 0,
            "script_version": 0,
            "script_key": "02c976ab7b107a005b285f0ac72803a34460145d17a9b8ac8a4a7f71315afbdba3",
            "asset_group": {
                "raw_group_key": "03222fd004d5b2b85a553e8149f96709b21d81b4ed709c2d7a2bf9124ea52411b5",
                "tweaked_group_key": "022e93c30c132c46519caf9004a99c163d2dda39036a7a081dc3d35e63e2c42917",
                "asset_id_sig": "30ed63b815a025d1587838961c84fc95b59c90771972d231ad6512d9ea9e7af4a3fce45fd0e1b8ffa90a07604307ec0f2f104180a58c3bf6d256fc70a7f60eb0"
            },
            "chain_anchor": {
                "anchor_tx": "020000000001019bd1822c6f79d6b1d8418d3d73237da0593aed6c5286f8fd1ae6568c606344f30100000000ffffffff02e8030000000000002251205a7adccedfe2860cca809cfbe700ffb7a65440fab73ff6b976aedc725591a85c7b10000000000000225120f9b93417805aea50cb4e5a3ae71f3ca965641f4c2ea3f55d4138c0b4437c87de0140e202407c55fe929cb22d913f471f8f24dccf31688b2e9c8647dcdeb09a1d9be650e56fe2399b33a016e233e85445530a2eba7e868f1f91b313dddd1b8fd30b0800000000",
                "anchor_txid": "a30d506ec674aeced488ab0434072485d0a9e30e0399b0241284b905cfa4437d",
                "anchor_block_hash": "12402acc5ca02d975d746effeba707d03e970309389de5290100000000000000",
                "anchor_outpoint": "a30d506ec674aeced488ab0434072485d0a9e30e0399b0241284b905cfa4437d:0",
                "internal_key": "0276e89f6ead3d3ab004253adf00205beff1779921ab63274dcb24984e32a75b96"
            }
        }
    ]
}

**Comment by gvonbergen** [comment]
Tried now again and it seems that the transaction works now after I've set-up a completely new lnd wallet. 

The setup is now
1 BTC test node
2 LND instances / wallets
2 tarod instances

sending from one tarod instance to the other.

Not sure why but maybe @guggero can explain as he basically gave the hint in https://github.com/lightninglabs/taro/issues/203#issuecomment-1375292289

here the result:
tarocli assets send --addr tarotb1qqqsqq3u9dgvxzk2ucj3c252p57wzu9af2xlppqdlzrhx4zzj859f64wyw9sqqqqqqp5ysj5pekhjgrdv9nkjceqd4hkueteqqqqqqqqqsssy70zafa5tr35ugtfg9tcpughcv0qe0wuh6m55hankvlvu8glkh2nqcssyrtvns792lc03hsw5nd97zzrj4543e4ztyzr026dmrps8l9typt6pqqku8ngsq9
{
    "transfer_txid": "2742a96e262a4b87e1a078d41c48eaaddf1a142c132bed701347c552a4b67e35",
    "anchor_output_index": 0,
    "transfer_tx_bytes": "0200000000010225cc9ba6ac37fafcd60d18273e04ba3e6dafc5238c1ea7f666feddd78ecdf7610100000000ffffffff25cc9ba6ac37fafcd60d18273e04ba3e6dafc5238c1ea7f666feddd78ecdf76100000000000000000003e803000000000000225120cfefc1ff9cf7712dd7efabd0a74e545e8acc7a7e2ce7a09284b4733862c62159e8030000000000002251200a4b62f75418b98d1dc611fce0a62b4556916c2d8fcd3148e29d01791e09c011b40c000000000000225120d59d2a664bb955d5ce724973034cf2c944a79dff3b6768a733bbbeae76895c7201407eb445cbe55a61d5cfeb05cf50f76fa900ced21bc34ab7c95c61b946d827b62bc235c44daf82636f88bd948b09a01a87ea4a80ab7f3777ec2af539392cc210c30140914eb4ec0e66f129a671fa070c33945cfdedc82f1bfa949b4cea0659bd5cfd558ce410afcea8dbc92e828e0feeec992535fcd91440e255403a2878e94e8b03fd00000000",
    "taro_transfer": {
        "old_taro_root": "5be8bd15d8ad54007d270b28e4ca1d18767e094d25e9b5d80d1e615b8b94c469",
        "new_taro_root": "0c1e7d8cb484e77a6fd068db0b0ad4a4cde75d8b8356c396290ae0e31319ed41",
        "prev_inputs": [
            {
                "anchor_point": "61f7cd8ed7ddfe66f6a71e8c23c5af6d3eba043e27180dd6fcfa37aca69bcc25:0",
                "asset_id": "d6543f269ddaa5cae6a59921738e95f8b9ebf78aa8835682b631b19c201d3a64",
                "script_key": "02d23db5aa9d035c725c1da81cee4669ad3d2034e262c95199b3bb71fca8027ad8",
                "amount": "500"
            }
        ],
        "new_outputs": [
            {
                "anchor_point": "2742a96e262a4b87e1a078d41c48eaaddf1a142c132bed701347c552a4b67e35:0",
                "asset_id": "d6543f269ddaa5cae6a59921738e95f8b9ebf78aa8835682b631b19c201d3a64",
                "script_key": "0217ca138c4a37cbcf1c3f2e1d35a9a7adab2facce30da108cd6c2be9e691f89d4",
                "amount": "390",
                "new_proof_blob": null,
                "split_commit_proof": null
            },
            {
                "anchor_point": "2742a96e262a4b87e1a078d41c48eaaddf1a142c132bed701347c552a4b67e35:1",
                "asset_id": "d6543f269ddaa5cae6a59921738e95f8b9ebf78aa8835682b631b19c201d3a64",
                "script_key": "0279e2ea7b458e34e2169415780f117c31e0cbddcbeb74a5fb3b33ece1d1fb5d53",
                "amount": "110",
                "new_proof_blob": null,
                "split_commit_proof": null
            }
        ]
    },
    "total_fee_sats": "257"
}

**Comment by jharveyb** [comment]
@gvonbergen  this was very helpful! I think I see the problem now. The asset was created with emission enabled, and so has a group key. But when I decode this address, it shows no group key. Can you try to generate the address with this command:

`tarocli ad n --genesis_bootstrap_info 9bd1822c6f79d6b1d8418d3d73237da0593aed6c5286f8fd1ae6568c606344f300000001044c4558350d7375706572206d6f6e657920350000000000 --group_key 022e93c30c132c46519caf9004a99c163d2dda39036a7a081dc3d35e63e2c42917 --amt 121`

**Comment by gvonbergen** [comment]
@jharveyb Can not retest as I deleted the original wallet. 
But when I did the re-test it also worked without mentioning the group_key. I minted the asset the same way with "enable_emission" and it didn't generate a group_key in the output


code:
tarocli2 addrs new --genesis_bootstrap_info 2b50c30acae6251c2a8a0d3ce170bd4a8df0840df88773544291e854eaae238b00000000034242540e6d79206d61676963206d6f6e65790000000000 --amt 110
{
    "encoded": "tarotb1qqqsqq3u9dgvxzk2ucj3c252p57wzu9af2xlppqdlzrhx4zzj859f64wyw9sqqqqqqp5ysj5pekhjgrdv9nkjceqd4hkueteqqqqqqqqqsssy70zafa5tr35ugtfg9tcpughcv0qe0wuh6m55hankvlvu8glkh2nqcssyrtvns792lc03hsw5nd97zzrj4543e4ztyzr026dmrps8l9typt6pqqku8ngsq9",
    "asset_id": "d6543f269ddaa5cae6a59921738e95f8b9ebf78aa8835682b631b19c201d3a64",
    "asset_type": "NORMAL",
    "amount": "110",
    **"group_key": null,**
    "script_key": "0279e2ea7b458e34e2169415780f117c31e0cbddcbeb74a5fb3b33ece1d1fb5d53",
    "internal_key": "020d6c9c3c557f0f8de0ea4da5f0843956958e6a2590437ab4dd8c303fcab2057a",
    "taproot_output_key": "0a4b62f75418b98d1dc611fce0a62b4556916c2d8fcd3148e29d01791e09c011"
}

**Comment by jharveyb** [comment]
@gvonbergen the group key should not show up in the output from the minting command, but should show up if you call `assets list`.

**Comment by snow884** [comment]
> Do things work if you use an `=` everywhere in the command for the CLI args vs a space (like it is rn)?


Hi @Roasbeef 

Yes using "=" solves the problem for me.

**Comment by snow884** [comment]
> Also, was the mint confirmed before you tried the send? Should be some log lines about it.

I could see a minted asset when I did `assets list` but the transaction still had 0 confirmations when this error occurred.

**Comment by snow884** [comment]
I am no longer getting the problem. I have done the following:

* used`=` after command line arguments - thanks @Roasbeef 
* used bitcoind instead of neutrino -
* waited until the minting transaction is confirmed onchain

**Comment by guggero** [comment]
Closing as solved by disabling emission (until that's fixed in an upcoming PR).
