### ISSUE TITLE
No tarod file generated

### ISSUE THREAD

**Issue by borislav-itskov** [lightninglabs/taro#271]
Hey guys,
I'm trying to install taro but, everything passes when I run make install but for some reason, I don't have the tarod / tarocli files generated in the /usr/local/go/bin folder.  
I'm running ubuntu 20.04 and want to use Polar with taro. I don't have a LND node running locally but I guess I don't need it since I'm using polar.
I tried with go versions 1.20 and 1.19.6. Both of them seem to install taro successfully or at least no error is being shown. When I rerun make install, this is what I get:
```
Installing tarod and tarocli.
GO111MODULE=on go install -v -tags="" -ldflags " -s -w -buildid= -X github.com/lightninglabs/taro.Commit=v0.1.1-alpha-211-g03f236f" github.com/lightninglabs/taro/cmd/tarod
GO111MODULE=on go install -v -tags="" -ldflags " -s -w -buildid= -X github.com/lightninglabs/taro.Commit=v0.1.1-alpha-211-g03f236f" github.com/lightninglabs/taro/cmd/tarocli

```
And that's it. Afterwards, I check the /usr/local/go/bin but no tarod file is present there.

**Comment by guggero** [comment]
Weird. What does your `$GOPATH` variable point to? Are you sure it's `/usr/local/go`? You can check with `go env`.

**Comment by borislav-itskov** [comment]
That was it, sorry to bother you. I installed it in /usr/local/go but the `$GOPATH` was different.  
Thanks a million.
