### ISSUE TITLE
rpc: enable ability to specify multiple assets to be minted belong to the same group

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#60]
As is, each time one creates an asset, if emission is enabled, then we'll generate a unique family key for each of them. However there're case where you want to mint a set of assets, with each asset having the same key family. An example of such a case is creating a series of collectibles, with the same key family, so they all reside in the same sub-tree. 

This should likely take the form of some sort of top-level identifier, similar to the exclusive groups in lnd's sweeper. Then during the minting process, we'd create one family key per identifier, and write them to disk in that manner. An e2e test would then ensure that all the assets were created w/ the same key family.

**Comment by dstadulis** [comment]
This issue is a duplicate of #142 
It should remain closed.
