### ISSUE TITLE
addr+rpc: add code paths for creating an address w/ a script path

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#75]
In #73 users can only make addresses that support key path spends. We want to also let them have ppl send to more complex scripts. 

One thing missing from the PR today is importing the addresses into the wallet once they've been created. The script path case would be similar: 
  * Allow a user to specify the serialized script (or a template, descriptor, etc) when making the address 
  * Store the full script leaves and also root on disk (extend the table, maybe add some more indexes) 
  * Import _all_ of this information into the wallet, which supports native script path storage

**Comment by dstadulis** [comment]
add some of the elements in the scriptkey 

The issue's work might be more designed focused
open design, how is the user going to spend this? will it force our hand to do PSBT design, 
will lnd and the wallet be aware of the necessary elements to perform this functionality 

Pool account is the perfect test vector to test
