### ISSUE TITLE
addr+bip-taro-addr: extend address scheme logic to work for collectibles and also full value sends

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taro#99]
This is related to #80. 

The address scheme is designed with a primary goal of the receiver being able to use the addr to watch on chain for the event that sends to their desired taro leaf/asset. When designing it, we were thinking mainly about normal assets (need splits, etc). We assumed that collectibles would be transfered with mainly swappy stuff. 

The case of sending a collectible, and a sender sending their entire balance to the receiver are essentially the same case. In both cases, since we want the receiver's TLV leaf to be able to be computed ahead of time. This means we need to again rely on the split locator scheme, with a slight twist: the thing anchoring the split commitment will actually be a _zero_ value asset. We could use some other type, like a special tombstone or w/e, but zero value assets seems simpler. 

With this in place, all the logic proceeds like normal, but now the anchor asset is a bit different. The proofs of exclusion (for complete sends) also need to be modified, as we'll ask for the proof, but then verify that either nothing committed to (zero value) or it's there but the sum is zero.

**Comment by arunned** [comment]
So far I am able to successfully send NORMAL asset but Error when trying to send a COLLECTIBLE asset  by generating an address. This error “FRTR: unable to advance state machine: send: Output indexes not starting at 0 and continuous”
tarocli addrs new --genesis_bootstrap_info a0501456187764700e37745da4e4a6bbd5343121ee89c636290b7f4c90961249000000010c737461726261636b726e66740f737461726261636b72206d6f6e65790000000001 --amt 1
{
    "encoded": "tarotb1qqqsqqjx5pgpg4scwaj8qr3hw3w6fe9xh02ngvfpa6yuvd3fpdl5eyykzfysqqqqqyx8xarpwf3xzcmtwfhxvaq0wd6xzunzv93kku3qd4hkueteqqqqqqqpqssv0mysls4gezf89qv7uax9tc330seydumh9pfj7v7c5k4y6sn60ecxyps8sfqzxpmfsnmme9pyscxtww7r2mgg9jlegha5ajyug3m7st5wqzqpqyg9j0w6",
    "asset_id": "79a1d6e525568007fd77a6891fdb1614bcc2169649b4aa9b2086ff89d524bd40",
    "asset_type": "COLLECTIBLE",
    "amount": "1",
    "family_key": null,
    "script_key": "02c7ec90fc2a8c89272819ee74c55e2317c3246f37728532f33d8a5aa4d427a7e7",
    "internal_key": "02607824023076984f7bc9424860cb73bc356d082cbf945fb4ec89c4477e82e8e0",
    "taproot_output_key": "e300af8ec2ccd99a99ceb0400ade288579163e5eabdaa7a78cf1a8362c0f2eb6"
}
tarocli assets send -addr tarotb1qqqsqqjx5pgpg4scwaj8qr3hw3w6fe9xh02ngvfpa6yuvd3fpdl5eyykzfysqqqqqyx8xarpwf3xzcmtwfhxvaq0wd6xzunzv93kku3qd4hkueteqqqqqqqpqss9fvpz5tme3d84v7fd5vxed87xq4ksl436dlf9ukegckn5e2mkmqsxyzxargq0kn9v0accq2jx9snshqawvg6tgev4v62wdykn3vvku3kckzqpqypeervl
[tarocli] unable to send assets: rpc error: code = Unknown desc = send: Output indexes not starting at 0 and continuous
:~/.taro/data/testnet/proofs$
Error messages from tarod
Sep 30 13:09:52 ip-172-31-82-100 tarod[1601]: 2022-09-30 13:09:52.666 [INF] FRTR: Received to send request to: 79a1d6e525568007fd77a6891fdb1614bcc2169649b4aa9b2086ff89d524bd40:0254b022a2f798b4f56792da30d969fc6056d0fd63a6fd25e5b28c5a74cab76d82
Sep 30 13:09:52 ip-172-31-82-100 tarod[1601]: 2022-09-30 13:09:52.666 [INF] FRTR: ChainPorter advancing from state=0 to state=10
Sep 30 13:09:52 ip-172-31-82-100 tarod[1601]: 2022-09-30 13:09:52.670 [INF] FRTR: Selected 1 possible asset inputs for send to 0254b022a2f798b4f56792da30d969fc6056d0fd63a6fd25e5b28c5a74cab76d82
Sep 30 13:09:52 ip-172-31-82-100 tarod[1601]: 2022-09-30 13:09:52.670 [DBG] TARO: Deriving new key for fam_family=219
Sep 30 13:09:52 ip-172-31-82-100 tarod[1601]: 2022-09-30 13:09:52.674 [DBG] TARO: Deriving new key for fam_family=219
Sep 30 13:09:52 ip-172-31-82-100 tarod[1601]: 2022-09-30 13:09:52.677 [INF] FRTR: Generating Taro witnesses for send to: 0254b022a2f798b4f56792da30d969fc6056d0fd63a6fd25e5b28c5a74cab76d82
Sep 30 13:09:52 ip-172-31-82-100 tarod[1601]: 2022-09-30 13:09:52.680 [INF] FRTR: Constructing new Taro commitments for send to: 0254b022a2f798b4f56792da30d969fc6056d0fd63a6fd25e5b28c5a74cab76d82

**Comment by Roasbeef** [comment]
Hi @arunned, that's expected until this issue is resolved. There's a pending PR (#159) that takes some initial steps towards fixing this issue.
